# Main composition file for Robot Application Container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore

version: '3.8'
services:
  # Application container
  robotappliance:
    container_name: robotappliance
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - "./scripts/:/robot/scripts/"
      - "/dev/:/dev/"
      - "/run/:/run/"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - "DISPLAY=:0"
      - "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"